name: basic-check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-tests-and-coverage:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - uses: artiomtr/jest-coverage-report-action@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 22.35 # optional parameter
  # https://github.com/marketplace/actions/run-eslint-with-reviewdog
  eslint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18.13'
          cache: 'yarn'
      - uses: actions/checkout@v3
      - name: Eslint check
        uses: reviewdog/action-eslint@v1
  web-e2e:
    needs: [unit-tests-and-coverage, eslint-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dispatch an event to trigger web's workflow and wait for e2e test result
        run: |
          curl \
            -X POST \
            -u "${{secrets.TRIGGER_WEB_USERNAME}}:${{secrets.TRIGGER_WEB_TOKEN}}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/flux3dp/beam-studio-web/actions/workflows/e2e.yml/dispatches \
            -d '{"ref": "master", "inputs": {"core_branch": "${{ github.event.pull_request.head.sha }}"}}'
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: flux3dp
          repo: beam-studio-web
          github_token: ${{ secrets.TRIGGER_WEB_TOKEN }}
          workflow_file_name: e2e.yml
          wait_interval: 300

