name: basic-check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.19]
        python-version: [3.7]
        os: [macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run unit tests
        run: yarn run spec
  coverage:
    needs: unit-test
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v2
      - uses: artiomtr/jest-coverage-report-action@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 15.1 # optional parameter
  web-e2e:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dispatch an event to trigger web's workflow and wait for e2e test result
        run: |
          curl \
            -X POST \
            -u "${{secrets.TRIGGER_WEB_USERNAME}}:${{secrets.TRIGGER_WEB_TOKEN}}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/flux3dp/beam-studio-web/actions/workflows/e2e.yml/dispatches \
            -d '{"ref": "master", "inputs": {"core_branch": "${{ github.event.pull_request.head.sha }}"}}'
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: flux3dp
          repo: beam-studio-web
          github_token: ${{ secrets.TRIGGER_WEB_TOKEN }}
          workflow_file_name: e2e.yml
          wait_interval: 300
  # https://github.com/marketplace/actions/run-eslint-with-reviewdog
  # eslint-check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Eslint check
  #       uses: reviewdog/action-eslint@v1
        # with:
        # remove this parameter due to this known issue: https://github.com/reviewdog/reviewdog/issues/848
        #   fail_on_error: true
